services:
  - type: web
    name: robo-7xx
    env: python
    plan: free
    autoDeploy: true
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app --bind 0.0.0.0:$PORT"
